apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-service-operator
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      name: external-service-operator
  template:
    metadata:
      labels:
        name: external-service-operator
    spec:
      serviceAccountName: external-service-operator
      containers:
        - name: external-service-operator
          # Replace this with the built image name
          image: crowdfox/external-service-operator:devel
          command:
          - external-service-operator
          - --zap-devel
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "external-service-operator"
