apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-service-operator
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - events
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - eso.crowdfox.com
  resources:
  - '*'
  verbs:
  - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-service-operator-deployment
  namespace: external-services
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - external-service-operator
  resources:
  - deployments/finalizers
  verbs:
  - update

