kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-service-operator
subjects:
- kind: ServiceAccount
  name: external-service-operator
  namespace: external-services
roleRef:
  kind: ClusterRole
  name: external-service-operator
  apiGroup: rbac.authorization.k8s.io
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-service-operator-deployment
  namespace: external-services
subjects:
- kind: ServiceAccount
  name: external-service-operator
roleRef:
  kind: Role
  name: external-service-operator-deployment
  apiGroup: rbac.authorization.k8s.io

